export default {
  APP_INIT: 'APP_INIT',
  REQUEST_IN_PROGRESS: 'REQUEST_IN_PROGRESS',
  TITLE_SELECTED: 'TITLE_SELECTED',
  VERSIONS_RECEIVED: 'VERSIONS_RECEIVED',
  TITLE_AVAILABLE: 'TITLE_AVAILABLE',
  CLOSE_GALLERY: 'CLOSE_GALLERY'
}