export default {
  APP_INIT: 'APP_INIT',
  REQUEST_IN_PROGRESS: 'REQUEST_IN_PROGRESS',
  TITLE_SELECTED: 'TITLE_SELECTED',
  VERSIONS_RECEIVED: 'VERSIONS_RECEIVED',
  CLOSE_GALLERY: 'CLOSE_GALLERY',
  EXPANDED_VIEW: 'EXPANDED_VIEW',
  GROUP_EXPANDED_VIEW: 'GROUP_EXPANDED_VIEW'
};
